Repository OpenSourceRaidGuild/atom-pwa, pull requests merged in 2021-02, with the labels that each got.

#1 installed Jest & React Testing Library
  package.json
  yarn.lock
Labels: Good First Issue, Type: Toolchain

#4 Setting up Jest
  babel.config.json
  jest.config.js
  jest/babelTransform.js
  jest/cssTransform.js
  jest/fileTransform.js
  jest/importMetaBabelPlugin.js
  package.json
  src/Locale.ts
  src/components/App.test.tsx
  src/setupTests.ts
  tsconfig.json
  yarn.lock
Labels: CTA: Help Wanted, Difficulty: Heroic, Priority: Critical 🚨, Type: Toolchain

#22 test: added test for modal
  src/components/shared/modal/modal.test.tsx
Labels: Difficulty: Beginner :nerd_face:, Items: Common, Items: Uncommon, Quest: Main, Raid: Boss, Type: Enhancement

#29 RTL additional libs
  package.json
  yarn.lock
Labels: Difficulty: Beginner :nerd_face:, Type: Toolchain

#30 Cypress + Cy RTL
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/smoke.spec.ts
  cypress/plugins/index.ts
  cypress/support/commands.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  jest.config.js
  package.json
  yarn.lock
Labels: Difficulty: Beginner :nerd_face:, Items: Common, Quest: Main, Raid: Boss, Type: Enhancement, Type: Feature, Type: Toolchain

#47 Test case for Button component
  src/components/shared/button/Button.test.tsx
Labels: Difficulty: Beginner :nerd_face:, Items: Common, Quest: Main, Raid: Boss, Status: Completed

#56 Adds tests for ThemeSelector
  src/components/shared/modal/Modal.tsx
  src/components/theme-selector/ThemeSelector.test.tsx
Labels: Difficulty: Beginner :nerd_face:, Items: Uncommon, Quest: Main, Raid: Boss, Type: Refactor, Type: Tests 🧪

#58 Cypress tests About and 404 routing & Adding to GH Action workflow
  .eslintrc
  .github/workflows/test.yml
  cypress/integration/About/About.spec.ts
  cypress/integration/Routes/404.spec.ts
  cypress/integration/smoke.spec.ts
  cypress/tsconfig.json
  package.json
  yarn.lock
Labels: Difficulty: Hardmode :mountain_bicyclist:, Items: Uncommon, Quest: Main, Raid: Boss, Side Quest: Group, Type: Tests 🧪

#60 Improve the tests for PeriodicTable.tsx
  src/components/periodic-table/PeriodicTable.test.tsx
  src/components/periodic-table/PeriodicTable.tsx
Labels: Difficulty: Beginner :nerd_face:, Items: Uncommon, Quest: Main, Raid: Boss, Type: Tests 🧪

#54 Adding tests for mass calculator
  src/components/element-picker/ElementPicker.test.tsx
  src/components/mass-calculator/MassCalculator.test.tsx
  src/components/periodic-table/PeriodicTable.test.tsx
  src/setupTests.ts
Labels: Difficulty: Beginner :nerd_face:, Items: Common, Quest: Main, Raid: Boss, Raid: Party, Status: In Progress 🚧, Status: Pending, Type: Tests 🧪

#64 Adding tests for Selector Modal
  src/components/shared/selector-modal/SelectorModal.test.tsx
Labels: Difficulty: Beginner :nerd_face:, Items: Common, Items: Uncommon, Quest: Main, Raid: Boss, Type: Tests 🧪

#67 Adding tests for Rate App component
  jest.config.js
  package.json
  src/components/rate-app/RateApp.test.tsx
  src/components/rate-app/RateApp.tsx
  yarn.lock
Labels: Difficulty: Beginner :nerd_face:, Items: Uncommon, Quest: Main, Raid: Boss, Status: Completed, Type: Tests 🧪, Type: Toolchain
