Repository OpenSourceRaidGuild/atom-pwa, pull requests merged in 2021-03, with the labels that each got.

#69 Spinner 50% -> 100%
  .github/workflows/test.yml
  cypress/integration/smoke.spec.ts
  src/components/shared/spinner/Spinner.test.tsx
  src/components/shared/spinner/Spinner.tsx
Labels: Difficulty: Beginner :nerd_face:, Items: Common, Quest: Main, Raid: Boss, Type: Tests 🧪

#78 Add tests to ValencesTest.tsx
  src/components/valences-test/ValencesTest.test.tsx
Labels: Difficulty: Hardmode :mountain_bicyclist:, Items: Rare, Items: Uncommon, Quest: Main, Side Quest: Group, Status: In Progress 🚧, Type: Tests 🧪

#84 Add tests for PeriodicTableTest.tsx
  src/components/periodic-table-test/PeriodicTableTest.test.tsx
  src/components/shared/swipeable-modal/SwipeableModal.tsx
Labels: Difficulty: Hardmode :mountain_bicyclist:, Items: Rare, Items: Uncommon, Quest: Main, Raid: Boss, Type: Tests 🧪

#92 Replace babel-preset-vite with published version
  jest/babel-preset-vite/babel-plugin-transform-vite-meta-env.js
  jest/babel-preset-vite/babel-plugin-transform-vite-meta-glob.js
  jest/babel-preset-vite/babel-preset-vite.js
  jest/babel-preset-vite/index.js
  jest/babelTransform.js
  package.json
  yarn.lock
Labels: Difficulty: Beginner :nerd_face:, Items: Rare, Items: Uncommon, Side Quest: Group, Side Quest: Solo, Type: Feature, Type: Refactor, Type: Tests 🧪, Type: Toolchain

#93 add unit tests for SwipeableModal.tsx
  src/components/shared/swipeable-modal/SwipeableModal.test.tsx
Labels: Difficulty: Heroic, Items: Epic, Items: Rare, Quest: Main, Raid: Boss, Raid: Party, Type: Tests 🧪

#98 refactor: converted modal to use hooks
  .betterer.results
  src/components/shared/modal/Modal.tsx
  src/components/shared/modal/modal.test.tsx
Labels: Difficulty: Beginner :nerd_face:, Items: Uncommon, Quest: Main, Raid: Boss, Status: Completed, Type: Refactor

#100 refactor: convert mass-calculator to use hooks
  src/components/mass-calculator/AddElementModal.tsx
  src/components/mass-calculator/CalculatorElement.tsx
  src/components/mass-calculator/EditElementModal.tsx
  src/components/mass-calculator/MassCalculator.tsx
  src/components/mass-calculator/hooks/useMassCalculator.ts
  src/components/mass-calculator/hooks/useModal.ts
Labels: Difficulty: Hardmode :mountain_bicyclist:, Quest: Main, Raid: Boss, Type: Enhancement, Type: Refactor

#158 Fixed deprecated types, null checks ect...
  src/components/main-menu/menu-entry/MenuEntry.tsx
  src/components/shared/spinner/Spinner.tsx
  src/components/valences-test/settings/ValencesTestSettings.tsx
Labels: Items: Common, Priority: Low 🍃, Raid: Trash Mobs, Side Quest: Solo, Type: Refactor

#159 refactor PeriodicTableTest.tsx to hooks
  src/components/periodic-table-test/PeriodicTableTest.tsx
  src/hooks/useInstance.ts
Labels: Difficulty: Hardmode :mountain_bicyclist:, Quest: Main, Raid: Boss, Status: In Progress 🚧, Type: Refactor

#156 Redesign SwipeableModal to use hook patterns
  src/components/shared/swipeable-modal/SwipeableModal.tsx
Labels: Difficulty: Hardmode :mountain_bicyclist:, Quest: Main, Raid: Boss, Status: Merge Conflict 🛑 🏗️, Type: Refactor

#161 convert PtElementTest to hooks
  src/components/periodic-table-test/PeriodicTableTest.tsx
  src/components/pt-element/PtElementTest.test.tsx
  src/components/pt-element/PtElementTest.tsx
Labels: Quest: Main, Raid: Boss, Type: Refactor

#160 Convert <ListItemSwipeAction /> to hooks
  src/components/shared/list-item-swipe-action/ListItemSwipeAction.tsx
  src/hooks/useLatestRef.tsx
Labels: Side Quest: Group, Type: Question, Type: Refactor

#171 Version exacted for Vite to 2.0.1
  .github/workflows/test.yml
  package.json
  yarn.lock
Labels: Type: Refactor, Type: Tests 🧪, Type: Toolchain

#191 Jacobmgevans
  .all-contributorsrc
Labels: Type: Documentation

#192 Documentation All Contributors
  README.md
Labels: Side Quest: Solo, Type: Documentation
